services:
  - type: web
    name: insta-downloader-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py

